services:
  - type: static_site
    name: starcraft-tmg-dice
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /preview
        destination: /index.html
      - type: rewrite
        source: /preview/*
        destination: /*
    branches:
      - branch: dev
    envVars:
      - key: RENDER
        value: "true"
